---
title: "Data Visualization"
author: "그림그려조"
date: "2023-06-28"
output: html_document
---

```{r setup, echo=FALSE, results=FALSE, include=FALSE}
library(data.table)
library(tidyverse)
library(readr)
library(ggplot2)
library(ggrepel)
library(ggthemes)
library(knitr)
```



```{r cars}
data <- read_csv('/Users/yang/Downloads/blood.csv', locale = locale(encoding = "CP949"))
df <- data %>% filter(시점 >= 2018)

# 연령대별
df[,1:9] %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)')) %>% 
  filter(시점 == "2022") %>% group_by(key) %>% 
  summarise(sum =sum(as.numeric(value))) %>%
  mutate(ratio = sum / sum(sum)) %>% 
  ggplot(aes(x = "", y = ratio, fill = key)) +
  geom_bar(stat="identity",position = 'fill', alpha=0.5) + 
  theme_bw()+ theme(legend.position = 'bottom') +
  coord_polar("y") +
  geom_text(aes("", label = paste0(round(ratio,3) * 100,"%")), size = 4,
            position = position_stack(vjust = 0.5)) + 
  theme(text = element_text(family = "AppleGothic")) +
  theme(panel.border = element_blank(), panel.grid = element_blank())+
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank())+
  scale_color_tableau() +
  scale_fill_tableau()  
      
  
# 시점차트 데이터
df[,1:9] %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)')) %>% 
  group_by(시점) %>% summarise(sum = sum(as.numeric(value))) %>% 
  ggplot(aes(x = 시점, y = sum, group = 1)) + 
  geom_point(color = "red") + 
  geom_line(color = "red", alpha = 0.5) + theme_bw()+
  xlab("year") + ylab("") + 
  theme(text = element_text(family = "AppleGothic"))+
  theme(panel.grid = element_blank())

# 혈액형별 데이터
f <- df[,c(1:3,19:26)] 
f %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)')) %>% 
  filter(시점 == 2022) %>% group_by(key) %>%
  mutate(new = ifelse(key == "RH(+)AB형" | key == "RH(-)AB형","AB형",
                     ifelse(key == "RH(+)B형" | key == "RH(-)B형","B형",
                            ifelse(key == "RH(+)O형"|key == "RH(-)O형","O형",
                                   ifelse(key == "RH(+)A형"| key == "RH(-)A형","A형", "0"))))) %>% 
  group_by(new) %>% 
  summarise(sum = sum(as.numeric(value))) %>%
  ggplot(aes(x = reorder(new,sum), y = sum, fill = new)) + 
  geom_col(alpha = 0.5) + theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  
  xlab("blood type") + ylab("") + guides(fill = "none") +
  theme(text = element_text(family = "AppleGothic"))+
  geom_text(position = position_stack(vjust = 0.5), 
            aes(y=sum, label = sum), vjust=0.3, hjust = 0.5) + 
  coord_flip() +
  theme(panel.grid = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_color_tableau() +
  scale_fill_tableau()  
   
# 직업별 데이터
df3 <- df[,c(1:3,10:18)] %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)')) %>% 
  filter(시점 == 2022) %>% group_by(key) %>% summarise(sum = sum(as.numeric(value))) %>%
  mutate(prop = round(sum/sum(sum),3)) %>% top_n(5)

df3 %>% ggplot(aes(x = "", y = prop, fill = key)) + 
  geom_bar(stat = 'identity', position = "fill", alpha = 0.7) + 
  theme_bw()+ theme(legend.position = 'bottom') +
  theme(text = element_text(family = "AppleGothic")) + 
  geom_text(position = position_stack(), 
            aes(label = scales::percent(prop))) +
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank())+
  scale_color_tableau() +
  scale_fill_tableau()  
  

# 성별별 데이터
df4 <- df[,c(1:3,10:18)] %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)'))
colnames(df4) <- c('혈액원', "시점", '성별','key', 'value')
df4 %>% filter(시점 == "2022") %>% group_by(성별) %>% 
  summarise(n = sum(as.numeric(value))) %>% 
  mutate(ratio = n / sum(n)) %>% 
  ggplot(aes(성별,ratio, fill = 성별)) + 
  geom_bar(stat="identity", alpha = 0.7)+ 
  theme_bw()+ theme(legend.position = 'bottom') +
  geom_text(position = position_stack(vjust = 0.5), 
            aes(y=ratio, label = scales::percent(ratio)), vjust=-0.2) + 
  theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5)) + ylab("ratio") +
  theme(text = element_text(family = "AppleGothic")) + 
  scale_color_tableau() +
  scale_fill_tableau()+
  theme(panel.grid = element_blank(),
        axis.title.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank())

# 지역별 데이터
dt <- df[,c(1:3,10:18)] %>% 
  gather(key = "key", value = "value", -c('혈액원', '시점','성별(1)')) %>% 
  filter(시점 == 2022) %>% group_by(혈액원) %>% 
  summarise(sum = sum(as.numeric(value))) %>%
  mutate(prop = round(sum/sum(sum),4)) %>% arrange(desc(sum))
kable(dt)
```


